version: '3.8'

services:
  client:
    build:
      context: ./client_container
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - network1

  server:
    build:
      context: ./server_container
      dockerfile: Dockerfile
    networks:
      - network1

networks:
  network1:
